#! -*- coding:utf-8 -*-

"""
@author:Conner
@version:1.0
@date:13-12-24
@description:词汇表积累
"""
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

glossary = {
    "unUsed": [
        'and', 'it', 'is', 'I', 'a', 'she', 'he', 'his', "i'm", 'for',
        'in', '&', 'etc', 'our', 'with', 'you', 'your', 'yours', 'we',
        'any', 'some', 'to', 'them', 'like', 'one', 'of', 'anyone', 'ours',
        'used', 'were', 'was', 'an', 'their', 'them', 'in', "it's", '.',
        '&lt;', 'other', 'can', 'all', 'its', 'a', 'b', 'c', 'd', 'e', 'f',
        'g', 'h', 'i', 'g', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
        't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '6',
        '7', '8', '9', '0', 'km', 'this', 'are', 'am', 'any', 'many',
        'much', 'what', 'where', 'why', 'how', 'or', 'the'
    ],
    "used": [
        'network cards', 'auto-negotiation', 'Internet Plug Connector',
        'ipad mini', 'ipad air', 'WiFi Router', 'Ethernet Network',
        'Antenna Booster', 'High Speed', 'USB Adapter', 'Apple iPad',
        'Protective Case', 'Cigarette Lighter', 'Power Expansion',
        'Car Charger', 'iPhone 4/4S', 'Case Cover', 'Skin Case',
        'Plastic Back', 'Screen Protector', 'Wireless Optical',
        'Optical Mouse', 'Bluetooth Speaker', 'Cell Phone Speaker',
        'USB Flash Drive', 'MP3 Player', 'MP4 Player', 'Android TV',
        'Apple  Accessories', 'iPad', 'Cases Skins', 'Screen Protectors',
        'iPhone3G/3GS', 'Mac', 'Chargers Docks', 'Case Skins',
        'Gadgets', 'iPod Accessories', 'iPhone 5', 'Silicone Cases',
        'Plastic Cases', 'Metal Cases', 'Leather Cases', 'iPad Mini',
        'iPad 4', 'Sim Card Gadget', 'Lens  Microscopes',
        'Anti-dust Plug', 'Styluse', 'Mounts  Holders', 'Other Gadgets',
        'Cables', 'Car Solutions', 'Earphones', 'Audio  Speakers',
        'Clearance Center', 'Bluetooth Keyboards', 'iPhone 5C',
        'iPhone 5S/5', 'iPad 2/3/4', 'Repair Parts  Tools', 'Car DVD Players',
        'Repair Parts', 'Repair Tools', 'Car  Accessories',
        'Car Alarms  Security', 'Alcohol Breath Tester', 'Car Alarms',
        'Locking Devices', 'Parking Sensors', 'Rearview Cameras',
        'Replacement Keys/Remotes', 'Car Beauty  Care', 'Air Fresheners',
        'Air Purifiers', 'Car Care', 'Car Cleaning Kits',
        'Car DVD Players', 'Single DIN Car DVD Players', 'Luxury Watches',
        'Headrest DVD Players', 'Overhead DVD Players', 'Jewelry Sets',
        'Sun Visor DVD Players', 'Double DIN Universal Car DVD Players',
        'Model Specific Double DIN Car DVD Players', 'DIY Jewelry',
        'Double DIN Car PC DVD Players', 'Nail Art', 'Mother of the Bride Dresses',
        'Model Specific Double DIN Car PC DVD Players',
        'Car Exterior decoration', 'Car Antenna', 'Car Badges',
        'Car Cover', 'Car Door Handles', 'Door Guards', 'Fuel Tank Covers',
        'Grille Guards', 'Mudguards', 'Other Exterior',
        'Car Interior decoration', 'Anti Slip Mat', 'Car Ashtrays',
        'Car Seat Covers  Cushions', 'Decorative Stickers',
        'GPS/Cellphone/Cup/CD/Device Holders', 'Other Interior',
        'Shoulder Pads/Buckles', 'Steering Wheel Cover', 'Sun Shade',
        'Tissue Box holder', 'Car Lights', 'Car LED Lights',
        'Decorative Lights', 'Fog Lights', 'HID Xenon Kits',
        'Warning Lights', 'LED Strip Lighting', 'Daytime Running Lights',
        'Car Parts', 'Air Pump Compressor', 'Brake Covers',
        'Car Tyre Pressure Meter', 'Exhaust', 'Fuel Economizer', 'Fuse',
        'Gauges', 'Hand  Repair Tools', 'Pedals  Pads', 'Shift Knobs',
        'Steering Wheel Spinner Knob', 'Tires', 'Windshield Wiper',
        'Car Power Adapter', 'Car Cigarette Lighter Socket',
        'Car Digital Charger', 'Car Inverter', 'GPSNavigation', 'Car GPS',
        'GPS Tracking Devices', 'Personalized', 'Car Key Case',
        'Car Key Chain', 'Goggles', 'Others', 'Car Audio and Monitors',
        'Car Audio', 'Car Monitors', 'FM Transmittercar mp3',
        'Bluetooth car kits', 'Car DVR', 'OBD  VAG', 'Cell Phones',
        'Android Phones', '35" android phones', '40" android phones',
        '43"-45" android phones', '47" android phones',
        '50" android phones', '53"-55" android phones',
        'above 55" android phones', 'Bar Phones', 'Cell Phone Accessories',
        'Interphones  Accessories', 'Watch cell Phones', 'Qwerty Phones',
        'Touch Screen Phones', 'Computers  Networking',
        'Bluetooth Adapters', 'Cables  Converters', 'Adapters',
        'Converters', 'Keyboards Mouse Input', 'Keyboard Mouse Combos',
        'Keyboards', 'Mouse', 'Laptop  Accessories', 'Batteries',
        'Cases  Bags', 'Chargers', 'Cooling Pads', 'Keyboard Skins',
        'Laptop Cleaners  Accessories', 'Laptops',
        'Microphones  Speakers', 'Headsets', 'Microphones', 'Speakers',
        'Networking', 'Router  Modems', 'TV Cards  Receivers',
        'Wireless/Wired Networking', 'CablesAntennas', 'Skype Phone',
        'PC Camera Webcams', 'PC Components  Accessories', 'Accessories',
        'Cooling Gear', 'Harddisk  Storage Device',
        'Harddisk Cases Dockings', 'USB Gadgets', 'USB Fan',
        'USB Home Improvement', 'USB Hub', 'USB Lamp', 'USB Flash Drives',
        'Printer Supplies  Accessories', 'Consumer Electronics',
        'Batteries  Chargers', 'Digital Photo Frames', 'Headphones',
        'MP3 MP4 MP5 Players', 'Spy Cameras', 'Electronics Tools',
        'Remote Controllers', 'Weinghing Scales', 'Plugs  Sockets',
        'Professional Tools', 'Card Readers  Adapters', 'Memory Cards',
        'CF Card', 'TF Card', 'SD Card', 'Cameras  Camcorders',
        'Cameras Bags', 'Tripods  Mounts', 'Batteries, Chargers  Cables',
        'Lenses, Flashes  Accessories', 'Android TV Player BOX',
        'Mini Wireless Mouse  Keyboards', 'Digital Terrestrial Receiver',
        'Projector  Telephones  Video glasses', 'LCD TV Wall Mounts',
        'Home  Garden', 'Home Security Systems', 'Alarm',
        'Doorbell  Accessories', 'Lock', 'Remote Control Accessories',
        'IP Surveillance', 'CCTV Products', 'Baby Monitors',
        'Office Equipment', 'Calculators', 'Microscopes  Magnifiers',
        'Other Office Equipment', 'Pens  Writing Instruments',
        'Notebooks  Notepads', 'Storage  Binding', 'Card Holders',
        'Pet Supplies', 'Kitchen  Dining', 'Ceramic Knives', 'Ice Trays',
        'Peelers  Slicers', 'Glassware  Drinkware', 'Flatware',
        'Bar Tools', 'Bakeware', 'Kitchen Tools  Gadgets',
        'Small Kitchen Appliances  Electronics',
        'Kitchen Storage  Organization', 'Kitchen Cleaning Supplies',
        'Bath', 'Funny Towels', 'Toothbrush Holders',
        'Other Bath Supplies', 'Soap Dishes', 'Wall Hooks  Hangers',
        'Toilet Paper Storage  Covers', 'Household Sundries', 'Rain Gear',
        'Baby Supplies', 'Slippers  Gloves', 'Lighter Torches',
        'DIY Grow Kits', 'Other Household Sundries', 'Creativity Living',
        'Adult Toys', 'SexAid', 'Lighting', 'Table Lamp  Desk Lamp',
        'Night Lights', 'Light Accessories', 'LED Lights', 'Strip Lights',
        'Chandeliers 220V', 'Pendant Lights 220V', 'Wall Lamps 220V',
        'Recessed Lighting', 'Flush Mount Lights 110V',
        'Flush Mount Lights 220V', 'Chandeliers 110V',
        'Pendant Lights 110V', 'Wall Lamps 110V', 'Lasers',
        'Laser Pointers', 'Stage Lighting', 'Wireless Presenters',
        'Festive decoration', 'Christmas Supplies', 'Halloween Supplies',
        'Other Party Supplies', 'National Day', 'Faucets', 'Shower Heads',
        'Bathroom Sink Faucets', 'Kitchen Faucets', 'Bathtub Faucets',
        'Faucet Accessories', 'Home Decor', 'Clocks', 'Wall Clocks',
        'Alarm Clocks', 'Desk Clocks',
        'Decorative Pillows  Home Textiles', 'Wall Decor',
        'Candles  Holders', 'Table Decor  Hanging Decor',
        'Home Improvement', 'Home Cleaning Supplies',
        'Heating, Cooling  Air Conditioning',
        'Small Appliances  Electronics', 'Home Hardware Tools',
        'Home Storage  Organization', 'Insect  Pest Repellent',
        'LED Light Bulbs', 'Spot Bulbs', 'Ball Bulbs', 'Corn Bulbs',
        'Candle Bulbs', 'Car LED Light Bulbs', 'Bulb Accessories',
        'Toys  Hobbies', 'Collectibles', 'Animation Gadgets',
        'Models  Figures', 'DIY Models', 'Automobile Collectibles',
        'Preschool', 'Construction Bricks Sets', 'Learning Toys',
        'Baby Toys', 'Board Games', 'Musical Toys', 'Yo-Yos',
        'Novelty Toys', 'Rc Toys  Hobbies', 'Other RC Toys',
        'RC Helicopters', 'RC Vehicles', 'RC Repair Accessories',
        'RC Quadrocopters  Planes', 'Stuffed Toys  Dolls',
        'Pranks, Gags  Unique Gifts', 'Pranks', 'Gags', 'Unique Gifts',
        'Weapons  Military Toys', 'Solar Toys',
        'Buckyballs  Magnetic Gadgets', 'Buckyballs', 'Magnetic Gadgets',
        'Puzzles', 'Magic Cubes', 'Puzzle Cubes',
        'Magic Magician Supplies', 'Video Games', 'Xbox 360 Accessories',
        'PS3 Accessories', 'PSP Accessories', 'Wii Accessories',
        'Nintendo DS Accessories', 'PC Game Controllers',
        'Handheld Game Players', 'Game Repair Tools', 'Tablet PCs',
        'Tablet PC', '9-97" dual core processor', '79" quad core tablet',
        '8" Tablet', '7" Tablet', '9-97" tablet', '101" and above tablet',
        'Tablet PC Accessories', 'cases skins',
        'Protective Cases with Keyboard', 'screen  protectors',
        'Sports  Outdoor', 'Swimming Supplies', 'Golf Supplies',
        'Bicycle Accessories', 'Cycling Gear',
        'Bicycle Parts  Accessories', 'Ball Game', 'Football',
        'Basketball', 'Baseball', 'Miscellanenous Sports', 'Fishing',
        'Fishing Rods  Kits', 'Fishing hooks', 'Fishing Lines',
        'Fishing Reels', 'Fishing Accessories', 'Outdoor Supplies',
        'Binoculars  Telescopes', 'Compasses', 'Headlamps',
        'Outdoor Supplies Need', 'Camping', 'Outdoor Cookware',
        'Survival  Emergency Gear', 'Backpacks  Bags',
        'Exercise  Fitness', 'LED  Flashlights', 'Flashlight Accessories',
        'No Battery Flashlights', 'UV  IR Flashlights',
        'Xenon Flashlights', 'AA   Flashlights', 'AAA   Flashlights',
        '18650   Flashlights', 'CR123A /16340/14500Flashlights',
        'LED Keychains', 'Other  Batteries  Flashlights',
        'Skating  Skate Accessories', 'Walkie-talkie', 'Gopro Hero',
        'Hiking Hunting Climbing', 'Health  Beauty', 'Beauty',
        'Cosmetics', 'Cosmetic Brushes  Bags', 'Mirrors  Combs',
        'Face Beauty Tools', 'Nail Care  Polish', 'Hair Care',
        'Shaving  Hair Removal', 'Health', 'Thermometer  Body Tester',
        'Personal Care', 'Hearing Aids', 'Foot Care', 'Oral Care',
        'Massage', 'Multifunctional Massagers', 'Targeted Massagers',
        'Wigs', 'Hair Wigs', 'Hair Extensions and Hairpieces',
        'E-Cigarettes  Accessories', 'E-Cigarettes',
        'E-Cigarette Accessories', 'Apparel  Accessories',
        "Men's Apparel", 'Jackets  Coats', 'Knitwear', 'T-shirts  Polo',
        'Shirts', 'Jeans  Pants', 'Beach Shorts', 'Shorts',
        "Women's Apparel", 'Blazers  Coats', 'Tops  Vests',
        'Shirts  Blouses', 'Dresses', 'Skirts', 'Tights  Socks',
        'Pants  Leggings', 'Swimwear', 'Sweatshirts  Hoodies',
        'Cosplay Costumes', 'Jewelry', 'Necklaces', 'Rings',
        'Stud Earrings', 'Bracelet', 'Brooches', 'Jewelry Sets',
        "Men's Cufflinks", 'Clip on earrings', 'Jewelry Boxes', 'Headwear',
        'Sweater Necklaces', 'Choker Necklaces', 'Drop Earrings',
        'Watches', "Men's watches", "Women's watches", 'Kid watches',
        'Couple Watches', 'LED Watches', 'Sport Watches', 'Pocket Watches',
        'Watch Accessories', 'Unisex Watches', 'Ring watches',
        'Mechanical Watches', 'Multi-movement Watches', 'Calendar Watches',
        'Ceramic Watches', 'Bracelet Watches', 'Glasses', 'Glasses Frames',
        '3D Glasses', 'Other Glasses  Accessories', "Men's Sunglasses",
        "Women's Sunglasses", 'Sport glasses', 'Presbyopic glasses',
        'Fashion Bags', "Women's bags", "Men's bags",
        'Luggage  Backpacks', 'Wallets  Cases', 'Keychains',
        'Other Accessories', 'Samsung Cellphone Cases Skins',
        'Galaxy Note 3', 'Galaxy S4/I9500', 'Galaxy Note 2/N7100',
        'Galaxy S3/I9300', 'Other Samsung Model',
        'Other Brand Cases Skins', 'HTC', 'Sony', 'Other Brands',
        'Samsung Screen Protectors', 'Other Brand Screen Protectors',
        'Bluetooth Headsets', 'Chargers  Solar Chargers',
        'Cables  Adapters', 'Mount  Stand', 'Cell Phones Jewelry',
    ]
}